[package]
name = "polling-multithread-test"
version = "0.1.0"
edition = "2021"

[dependencies]
async-channel = "1.8.0"
fastrand = "1.8.0"
futures-lite = "1.12.0"
polling = { path = "./polling" }

[workspace]
members = [
    "polling",
]
